"""initial schema

Revision ID: b2cf599cf690
Revises: 
Create Date: 2026-06-23 16:48:43.538409
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

revision: str = 'b2cf599cf690'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_type', sa.Enum('text', 'word', 'pdf', 'png', name='sourcetype'), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('raw_ref', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('received', 'processing', 'ready', 'failed', name='documentstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rulechunk',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('embedding_ref', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('canvasstate',
    sa.Column('document_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.PrimaryKeyConstraint('document_id')
    )
    op.create_table('run',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('document_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('running', 'done', 'failed', name='runstatus'), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('run', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_run_document_id'), ['document_id'], unique=False)

    op.create_table('taxonomynode',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('document_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('parent_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['taxonomynode.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('taxonomynode', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_taxonomynode_document_id'), ['document_id'], unique=False)

    op.create_table('view',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('document_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('kind', sa.Enum('flowchart', 'mindmap', 'project', name='viewkind'), nullable=False),
    sa.Column('payload', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('view', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_view_document_id'), ['document_id'], unique=False)

    op.create_table('auditevent',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('run_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('document_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('actor', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('payload', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('auditevent', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auditevent_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_auditevent_run_id'), ['run_id'], unique=False)

    op.create_table('checklistitem',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('document_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('taxonomy_node_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('checked', sa.Boolean(), nullable=False),
    sa.Column('source_unit_ids', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.ForeignKeyConstraint(['taxonomy_node_id'], ['taxonomynode.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('checklistitem', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_checklistitem_document_id'), ['document_id'], unique=False)

    op.create_table('infounit',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('document_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('provenance', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('taxonomy_node_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('merged_into_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.ForeignKeyConstraint(['merged_into_id'], ['infounit.id'], ),
    sa.ForeignKeyConstraint(['taxonomy_node_id'], ['taxonomynode.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('infounit', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_infounit_document_id'), ['document_id'], unique=False)

    op.create_table('conflict',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('document_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('left_unit_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('right_unit_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('open', 'resolved', name='conflictstatus'), nullable=False),
    sa.Column('resolution', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.ForeignKeyConstraint(['left_unit_id'], ['infounit.id'], ),
    sa.ForeignKeyConstraint(['right_unit_id'], ['infounit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conflict', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conflict_document_id'), ['document_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conflict', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conflict_document_id'))

    op.drop_table('conflict')
    with op.batch_alter_table('infounit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_infounit_document_id'))

    op.drop_table('infounit')
    with op.batch_alter_table('checklistitem', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_checklistitem_document_id'))

    op.drop_table('checklistitem')
    with op.batch_alter_table('auditevent', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auditevent_run_id'))
        batch_op.drop_index(batch_op.f('ix_auditevent_document_id'))

    op.drop_table('auditevent')
    with op.batch_alter_table('view', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_view_document_id'))

    op.drop_table('view')
    with op.batch_alter_table('taxonomynode', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_taxonomynode_document_id'))

    op.drop_table('taxonomynode')
    with op.batch_alter_table('run', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_run_document_id'))

    op.drop_table('run')
    op.drop_table('canvasstate')
    op.drop_table('rulechunk')
    op.drop_table('document')
    # ### end Alembic commands ###
